Abort if no devices attached

diff --git a/bin/adb-demo-off b/bin/adb-demo-off
--- a/bin/adb-demo-off
+++ b/bin/adb-demo-off
@@ -1,5 +1,12 @@
 #!/usr/bin/env bash
 
+if ! adb devices | tail +2 | grep device > /dev/null ; then
+  echo "error: no devices attached"
+  exit 1
+fi
+
+# Adds dynamic information from the status bar
+
 adb shell am broadcast -a com.android.systemui.demo -e command exit
 adb shell settings put global sysui_demo_allowed 0
 
diff --git a/bin/adb-demo-on b/bin/adb-demo-on
--- a/bin/adb-demo-on
+++ b/bin/adb-demo-on
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if ! adb devices | tail +2 | grep device > /dev/null ; then
+  echo "error: no devices attached"
+  exit 1
+fi
+
 # Removes dynamic information from the status bar
 
 adb shell settings put global sysui_demo_allowed 1
