Make more robust

diff --git a/bin/adb-demo-on b/bin/adb-demo-on
--- a/bin/adb-demo-on
+++ b/bin/adb-demo-on
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+# Abort entire script if any command fails
+# https://stackoverflow.com/a/821419
+set -e
+set -o pipefail
+
 if ! adb devices | tail -n +2 | grep device > /dev/null ; then
   echo "error: no authorized devices attached"
   exit 1
