Updates

diff --git a/bin/android-emulator b/bin/android-emulator
--- a/bin/android-emulator
+++ b/bin/android-emulator
@@ -145,17 +145,21 @@ install_cli_tools() {
 
   local sdkmanager_path="${install_dir}/bin/sdkmanager"
   # Conditionally patch sdkmanager to fix a quoting bug
+  # shellcheck disable=SC2016
   if grep -q 'JAVA_VER=$($JAVACMD' "${sdkmanager_path}"; then
     echo "Patching sdkmanager to fix quoting bug..."
     cp "${sdkmanager_path}" "${sdkmanager_path}.backup"
+    # shellcheck disable=SC2016
     sed -i '' 's/JAVA_VER=$($JAVACMD/JAVA_VER=$("$JAVACMD"/g' "${sdkmanager_path}"
   fi
 
   local avdmanager_path="${install_dir}/bin/avdmanager"
   # Conditionally patch avdmanager to fix a quoting bug
+  # shellcheck disable=SC2016
   if grep -q 'JAVA_VER=$($JAVACMD' "${avdmanager_path}"; then
     echo "Patching avdmanager to fix quoting bug..."
     cp "${avdmanager_path}" "${avdmanager_path}.backup"
+    # shellcheck disable=SC2016
     sed -i '' 's/JAVA_VER=$($JAVACMD/JAVA_VER=$("$JAVACMD"/g' "${avdmanager_path}"
   fi
 }
@@ -266,12 +270,11 @@ create_avd() {
 
   # Check if the image is installed, and install it if it's not
   local installed_packages
-  installed_packages=$("${sdkmanager}" --list_installed)
+  installed_packages=$(env SKIP_JDK_VERSION_CHECK=1 "${sdkmanager}" --list_installed)
   if ! echo "${installed_packages}" | grep -q "${image_package}"; then
     echo "System image '${image_package}' not found. Installing..."
-    yes | "${sdkmanager}" --licenses > /dev/null
-    "${sdkmanager}" --install "${image_package}"
-    if [[ $? -ne 0 ]]; then
+    yes | env SKIP_JDK_VERSION_CHECK=1 "${sdkmanager}" --licenses > /dev/null
+    if ! env SKIP_JDK_VERSION_CHECK=1 "${sdkmanager}" --install "${image_package}"; then
       echo "Failed to install system image '${image_package}'. Please check if the package name is valid." >&2
       exit 1
     fi
@@ -280,11 +283,34 @@ create_avd() {
   fi
 
   echo "Creating AVD '${avd_name}' with image '${image_package}'..."
+  # TODO: enable different device definitions ("wearos_large_round")
   echo "no" | "${avdmanager}" create avd -n "${avd_name}" -k "${image_package}" -d "wearos_large_round"
 }
 
 start_avd() {
-  require emulator adb
+  require emulator adb grep cut sed
+
+  local avd_ini="$HOME/.android/avd/$1.ini"
+  if [[ ! -f "$avd_ini" ]]; then
+    echo "$(basename "$0"): AVD '$1' does not exist." >&2
+    exit 1
+  fi
+
+  local avd_path
+  avd_path=$(grep "path=" "$avd_ini" | cut -d'=' -f2)
+
+  local image_sysdir
+  image_sysdir=$(grep "image.sysdir.1" "$avd_path/config.ini" | cut -d'=' -f2)
+
+  if [[ ! -d "$ANDROID_HOME/$image_sysdir" ]]; then
+    local package_id
+    package_id=$(echo "$image_sysdir" | sed 's/\//;/g' | sed 's/;$//')
+    
+    echo "$(basename "$0"): The system image required by this AVD is missing." >&2
+    echo "To install it, run:" >&2
+    echo "  \"$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager\" --install \"$package_id\""
+    exit 1
+  fi  
 
   local emulator_path="$ANDROID_HOME/emulator/emulator"
   if [[ ! -f "${emulator_path}" ]]; then
@@ -473,6 +499,5 @@ case "$1" in
   *)
     echo "$(basename "$0"): unknown command '$1'" >&2
     usage
-    exit 1
     ;;
 esac
