Support zipped apps

diff --git a/bin/apk-cat-manifest b/bin/apk-cat-manifest
--- a/bin/apk-cat-manifest
+++ b/bin/apk-cat-manifest
@@ -3,6 +3,7 @@
 require() { hash "$@" || exit 127; }
 
 require apkanalyzer
+require unzip
 require xmllint
 
 if [ -z "$1" ]; then
@@ -10,4 +11,24 @@ if [ -z "$1" ]; then
   exit 1
 fi
 
-apkanalyzer manifest print "$1" | xmllint --format -
+if [[ $1 == *.zip ]]; then
+
+  TMPDIR=$(mktemp -d)
+  trap 'rm -rf -- "$TMPDIR"' EXIT
+
+  unzip -q "$1" -d "$TMPDIR"
+  APKS=("$TMPDIR"/*.apk)
+  BASEAPK=("$TMPDIR"/*_base_split.apk)
+
+  if [ ! -f "${BASEAPK[0]}" ]; then
+    echo "error: *_base_split.apk not found in zip, aborting"
+    exit 1
+  fi
+
+else
+
+  BASEAPK="$1"
+
+fi
+
+apkanalyzer manifest print "$BASEAPK" | xmllint --format -
