Support installing via zip files

diff --git a/bin/apk-install-and-launch b/bin/apk-install-and-launch
--- a/bin/apk-install-and-launch
+++ b/bin/apk-install-and-launch
@@ -1,17 +1,63 @@
 #!/usr/bin/env bash
 
+# If this script breaks, it's probably because apkanalyzer doesn't
+# work. See if running "apkanalyzer" by itself emits its help page, or
+# an error. If an error, you probably want to check that JAVA_HOME is
+# set to the right version of java.
+
 require() { hash "$@" || exit 127; }
+
+shopt -s nullglob
 
 require adb
 require apkanalyzer
 
+while getopts "f" opt; do
+  case $opt in
+    f)
+      UNINSTALL=true
+	  ;;
+	*)
+	  ;;
+  esac
+done
+shift $((OPTIND-1))
+
 if [ -z "$1" ] || [ ! -f "$1" ]; then
-  echo "usage: $(basename "$0") <apk>"
+  echo "usage: [-f] $(basename "$0") <apk>"
   exit 1
 fi
 
-PACKAGE=$(apkanalyzer manifest application-id "$1")
+if [[ $1 == *.zip ]]; then
 
-# Should add support for a -f switch or something
-# adb uninstall "$PACKAGE"
-adb install -g -t -r "$1" && adb shell monkey -p "$PACKAGE" -c android.intent.category.LAUNCHER 1
+  TMPDIR=$(mktemp -d)
+  trap 'rm -rf -- "$TMPDIR"' EXIT
+
+  unzip "$1" -d "$TMPDIR"
+  APKS=("$TMPDIR"/*.apk)
+  BASEAPK=("$TMPDIR"/*_base_split.apk)
+
+  if [ ! -f "${BASEAPK[0]}" ]; then
+    echo "error: *_base_split.apk not found in zip, aborting"
+	exit 1
+  fi
+
+  PACKAGE=$(apkanalyzer manifest application-id "${BASEAPK[0]}")
+
+  if [ $UNINSTALL ]; then
+    adb uninstall "$PACKAGE"
+  fi
+  adb install-multiple -g -t -r "${APKS[@]}"
+  adb shell monkey -p "$PACKAGE" -c android.intent.category.LAUNCHER 1
+
+else # assume regular APK
+
+  PACKAGE=$(apkanalyzer manifest application-id "$1")
+
+  if [ $UNINSTALL ]; then
+    adb uninstall "$PACKAGE"
+  fi
+  adb install -g -t -r "$1"
+  adb shell monkey -p "$PACKAGE" -c android.intent.category.LAUNCHER 1
+
+fi
