Add node version detection

diff --git a/bin/envrc-init-node b/bin/envrc-init-node
--- a/bin/envrc-init-node
+++ b/bin/envrc-init-node
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 
-VERSION=${1:-7.2.0}
+if [ ! -d "$NODE_VERSIONS" ]; then
+  echo "error: NODE_VERSIONS not set, or not a directory"
+  exit 1
+fi
+
+VERSION=${1:-$(ls -r $NODE_VERSIONS | head -1 | sed -e 's/node-v//')}
 
 if [ ! -e ".envrc" ]; then
   echo "$(basename $0): creating .envrc"
