Check firebase project exists

diff --git a/bin/firebase-envrc b/bin/firebase-envrc
--- a/bin/firebase-envrc
+++ b/bin/firebase-envrc
@@ -1,21 +1,27 @@
 #!/usr/bin/env bash
 
 if [ $# == 0 ]; then
-  echo "usage: $(basename $0) firebase_app_name [custom_url] # see https://console.firebase.google.com/"
+  echo "usage: $(basename $0) firebase_project_id [custom_url] # see https://console.firebase.google.com/"
   exit 1
 fi
 
 if [ ! $(which direnv) ]; then
-  echo "error: direnv command not found"
+  echo "error: command direnv not found"
   exit 1
 fi
 
-FIREBASE_APP_URL="${2:-https://${1}.firebaseapp.com}/"
+FIREBASE_PROJECT_ID="$1"
+FIREBASE_PROJECT_URL="${2:-https://${1}.firebaseapp.com}/"
+
+if ! firebase list | grep -q "$FIREBASE_PROJECT_ID" ; then
+  echo "error: $FIREBASE_PROJECT_ID not a configured project (see firebase list)"
+  exit 1
+fi
 
 cat << END > .envrc
 # Must be an id from "firebase list"
 export FIREBASE_PROJECT_ID=$1
-export FIREBASE_PROJECT_URL=$FIREBASE_APP_URL
+export FIREBASE_PROJECT_URL=$FIREBASE_PROJECT_URL
 END
 
 echo "$(basename $0): created .envrc"
