Update firebase-*

diff --git a/bin/firebase-init b/bin/firebase-init
--- a/bin/firebase-init
+++ b/bin/firebase-init
@@ -1,5 +1,15 @@
 #!/usr/bin/env bash
 
+if [ -f firebase.json ]; then
+  echo "error: firebase.json already exists, aborting"
+  exit 1
+fi
+
+if [ -f .firebaserc ]; then
+  echo "error: .firebaserc already exists, aborting"
+  exit 1
+fi
+
 if [ "$FIREBASE_APP_NAME" = "" ]; then
   echo "error: FIREBASE_APP_NAME environment variable not set (run firebase-envrc)"
   exit 1
@@ -7,17 +17,29 @@ fi
 
 PUBLIC=${1:-.}
 
+mkdir -p "$PUBLIC"
+
+# https://firebase.google.com/docs/hosting/full-config
 cat << FIREBASE_JSON_END > firebase.json
 {
-  "firebase": "$FIREBASE_APP_NAME",
-  "public": "$PUBLIC",
-  "ignore": [
-    "firebase.json",
-    "**/.*",
-    "**/node_modules/**"
-  ]
+  "hosting": {
+    "public": "$PUBLIC",
+    "ignore": [
+      "firebase.json",
+      "**/.*",
+      "**/node_modules/**"
+    ]
+  }
 }
 FIREBASE_JSON_END
+
+cat << FIREBASERC_END > .firebaserc
+{
+  "projects": {
+    "default": "$FIREBASE_APP_NAME"
+  }
+}
+FIREBASERC_END
 
 cat << ROBOTS_TXT_END > "$PUBLIC/robots.txt"
 User-agent: *
