Improve gae-* scripts

diff --git a/bin/gae-update b/bin/gae-update
--- a/bin/gae-update
+++ b/bin/gae-update
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 
+if [ $( find . | wc -l ) -gt 10000 ]; then
+  echo "error: more than 10000 files"
+  exit 1
+  # GAE only supports 10k files, and you can't blacklist via app.yaml
+fi
+
 if [ ! -f app.yaml ]; then
   echo "error: no app.yaml found (create one with gae-init)"
   exit 1
@@ -18,6 +24,7 @@ fi
 # https://console.developers.google.com/project/$GAE_APP_ID
 appcfg.py --oauth2 -A $GAE_APP_ID update .
 
+echo "# https://console.developers.google.com/project/$GAE_APP_ID"
 echo "# http://$GAE_APP_ID.appspot.com/"
 
 if [ "$GAE_URL" != "" ]; then
