Better error handling

diff --git a/bin/gae-envrc b/bin/gae-envrc
--- a/bin/gae-envrc
+++ b/bin/gae-envrc
@@ -5,6 +5,11 @@ if [ $# == 0 ]; then
   exit 1
 fi
 
+if [ ! $(which direnv) ]; then
+  echo "error: direnv command not found"
+  exit 1
+fi
+
 cat << END > .envrc
 export GAE_APP_ID=$1
 export GAE_URL=$2
