Improve script

diff --git a/bin/gae-update b/bin/gae-update
--- a/bin/gae-update
+++ b/bin/gae-update
@@ -6,9 +6,20 @@ if [ ! -f app.yaml ]; then
 fi
 
 if [ ! $(which appcfg.py) ]; then
-  echo "error: appcfg.py not found (get the Google Appe Engine SDK for Python)"
+  echo "error: appcfg.py not found (see https://cloud.google.com/sdk/)"
   exit 1
 fi
 
-# https://console.developers.google.com/project/second-impact
-appcfg.py --oauth2 -A second-impact update .
+if [ "$GAE_APP_ID" = "" ]; then
+  echo "error: GAE_APP_ID environment variable not set (see https://console.developers.google.com/project)"
+  exit 1
+fi
+
+# https://console.developers.google.com/project/$GAE_APP_ID
+appcfg.py --oauth2 -A $GAE_APP_ID update .
+
+echo "# http://$GAE_APP_ID.appspot.com/"
+
+if [ "$GAE_URL" != "" ]; then
+  echo "# $GAE_URL"
+fi
