Add shellcheck and make some fixes

diff --git a/bin/mp4togif b/bin/mp4togif
--- a/bin/mp4togif
+++ b/bin/mp4togif
@@ -8,17 +8,17 @@ require() { hash "$@" || exit 127; }
 require ffmpeg
 
 if [[ $# -ne 1 ]]; then
-  echo "usage: $(basename $0) file.mp4"
+  echo "usage: $(basename "$0") file.mp4"
   exit 1
 fi
 
 if [[ ! -f "$1" ]]; then
-  echo "$(basename $0): $1: No such file"
+  echo "$(basename "$0"): $1: No such file"
   exit 1
 fi
 
 if [[ $(basename "$1" .mp4) = "$1" ]]; then
-  echo "$(basename $0): $1 is not an MP4"
+  echo "$(basename "$0"): $1 is not an MP4"
   exit 1
 fi
 
@@ -26,23 +26,22 @@ src="$1"
 dst=$(basename "$1" .mp4).gif
 
 if [[ -e "$dst" ]]; then
-  echo "$(basename $0): $dst already exists"
+  echo "$(basename "$0"): $dst already exists"
   exit 1
 fi
 
-palette=$(mktemp -t XXXXXXXXXXX.png)
-if [[ $? -ne 0 ]]; then
-  echo "$(basename $0): can't create temporary file"
+if ! palette=$(mktemp -t XXXXXXXXXXX.png); then
+  echo "$(basename "$0"): can't create temporary file"
   exit 1
 fi
 
 filters="fps=15,scale=640:-1:flags=lanczos"
 
-ffmpeg -v warning -i "$src" -vf "$filters,palettegen" -y -f apng $palette
-ffmpeg -v warning -i "$src" -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -f gif "$dst"
+ffmpeg -v warning -i "$src" -vf "$filters,palettegen" -y -f apng "$palette"
+ffmpeg -v warning -i "$src" -i "$palette" -lavfi "$filters [x]; [x][1:v] paletteuse" -f gif "$dst"
 
-echo "$(basename $0): created $dst"
+echo "$(basename "$0"): created $dst"
 
-rm $palette
+rm "$palette"
 
 exit 0
