Add newline to abort message

diff --git a/bin/nodejs-install b/bin/nodejs-install
--- a/bin/nodejs-install
+++ b/bin/nodejs-install
@@ -190,7 +190,7 @@ fi
 #
 
 if [[ -d $TARGET ]]; then
-  printf "${COLOR_ERROR}'%s' already exists...aborting!${COLOR_NORMAL}" $TARGET >&2
+  printf "${COLOR_ERROR}'%s' already exists...aborting!${COLOR_NORMAL}\n" $TARGET >&2
   exit 1
 fi
 
