adb related improvements

diff --git a/bin/packagename-logcat b/bin/packagename-logcat
--- a/bin/packagename-logcat
+++ b/bin/packagename-logcat
@@ -9,4 +9,11 @@ if [ -z "$1" ]; then
   exit 1
 fi
 
-adb shell pidof "$1"
+PID=$(adb shell pidof "$1")
+
+if [ -z "$PID" ]; then
+  echo "error: can't get pid of $1"
+  exit 1
+fi
+
+adb logcat --pid=$PID
