If using tsc, probably want minimal eslint config too

diff --git a/bin/tsc-init b/bin/tsc-init
--- a/bin/tsc-init
+++ b/bin/tsc-init
@@ -1,7 +1,15 @@
 #!/usr/bin/env bash
 
-if [ -f tsconfig.json ]; then
-  echo "error: tsconfig.json already exists, aborting"
+TSCONFIG_JSON="tsconfig.json"
+ESLINTRC_JSON=".eslintrc.json"
+
+if [ -f $TSCONFIG_JSON ]; then
+  echo "error: $TSCONFIG_JSON already exists, aborting"
+  exit 1
+fi
+
+if [ -f $ESLINTRC_JSON ]; then
+  echo "error: $ESLINTRC_JSON already exists, aborting"
   exit 1
 fi
 
@@ -10,7 +18,7 @@ if [ ! $(which tsc) ]; then
   exit 1
 fi  
 
-cat << TSCONFIG_JSON_END > tsconfig.json
+cat << TSCONFIG_JSON_END > $TSCONFIG_JSON
 {
   "compilerOptions": {
     "module": "commonjs",
@@ -25,3 +33,13 @@ cat << TSCONFIG_JSON_END > tsconfig.json
   ]
 }
 TSCONFIG_JSON_END
+
+# Configure eslint to not complain about tsc's .js files
+cat << ESLINTRC_JSON_END > $ESLINTRC_JSON
+{
+  "installedESLint": true,
+  "env": {
+    "es6": true
+  }
+}
+ESLINTRC_JSON_END
