Cleanup (big)

diff --git a/update b/update
--- a/update
+++ b/update
@@ -12,7 +12,7 @@
 #   https://dl.google.com/dl/cloudsdk/release/install_google_cloud_sdk.bash
 #   http://tim.theenchanter.com/2009/02/how-to-escape-arguments-in-bash.html?showComment=1321001720427#c4751431215627296974
 function x {
-  echo "$" "$@"
+  #echo "$" "$@"
   eval $(printf '%q ' "$@")
 }
 
@@ -26,6 +26,10 @@ function xmkdir {
 # Returns success if found
 function exists {
   type -P "$1" > /dev/null
+}
+
+function heading {
+  printf '# %s\n' "$@"
 }
 
 # SRCDIR is the root of the git repo
@@ -95,86 +99,10 @@ xmkdir "$LOCAL"
 BINDIR="$LOCAL/bin"
 xmkdir "$BINDIR"
 
-# Sublime Text
-
-# http://www.sublimetext.com/docs/3/projects.html - project specific configuration
-
-# if [ ! `which subl` ]; then
-#   if [ -d "/Applications/Sublime Text.app" ]; then
-#     x ln -sf "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" "$BINDIR/subl"
-#   fi
-# fi
-
-# if [ `which subl` ]; then
-
-#   if [ "$PLATFORM" = "linux" ]; then
-#     DST="$DSTDIR/.config/sublime-text-3/Packages/User"
-#   else
-#     DST="$DSTDIR/Library/Application Support/Sublime Text 3/Packages/User"
-#   fi
-
-#   xmkdir "$DST"
-
-#   if [ ! -L "$DST/Preferences.sublime-settings" ]; then
-#     x rm -f "$DST/Preferences.sublime-settings"
-#     x ln -sf "$SRCDIR/etc/subl/Preferences.sublime-settings" "$DST/Preferences.sublime-settings"
-#   fi
-
-#   # https://sublime.wbond.net/docs/syncing
-#   if [ ! -L "$DST/Package Control.sublime-settings" ]; then
-#     x rm -f "$DST/Package Control.sublime-settings"
-#     x ln -sf "$SRCDIR/etc/subl/Package Control.sublime-settings" "$DST/Package Control.sublime-settings"
-#   fi
-
-#   for d in Linux OSX Windows ; do
-#     if [ ! -L "$DST/Default ($d).sublime-keymap" ]; then
-#       x rm -f "$DST/Default ($d).sublime-keymap"
-#       x ln -sf "$SRCDIR/etc/subl/Default.sublime-keymap" "$DST/Default ($d).sublime-keymap"
-#     fi
-#   done
-
-# fi
-
-# Atom
-
-# Install atom, apm via the "Atom > Install Shell Commands" menu option
-
-# if [ false -a "$(which atom)" ]; then
-
-#   DST="$DSTDIR/.atom"
-
-#   xmkdir "$DST"
-
-#   for f in $SRCDIR/etc/atom/* ; do
-
-#     if [ ! -L "$DST/$(basename $f)" ]; then
-#       x rm -rf "$DST/$(basename $f)"
-#       x ln -sf "$f" "$DST"
-#     fi
-
-#   done
-
-# fi
-
-# if [ false -a "$(which apm)" ]; then
-
-#   packages="atom-beautify docblockr highlight-selected language-fish-shell linter linter-eslint minimap"
-
-#   for p in $packages ; do
-#     if ! apm list -ib | grep -q $p ; then
-#       x apm install $p
-#     fi
-#   done
-
-#   x apm upgrade --no-confirm
-
-# fi
-
-# Keybindings and other settings
-
 case "$PLATFORM" in
 
   darwin )
+    heading "macos"
     # For some reason *some* applications (like TextEdit) won't read
     # DefaultKeyBinding.dict if it's symlinked, or is in a symlinked directory,
     # so rsync instead of symlink... http://apple.stackexchange.com/a/53110/890
@@ -286,11 +214,18 @@ case "$PLATFORM" in
     # iA Writer: bind cmd-n to new file, instead of new file in library
     x defaults write pro.writer.mac NSUserKeyEquivalents -dict-add "New" -string "@n"
     # iA Writer: change default extension
-    x defaults write pro.writer.mac "Default Path Extension" -string "md"
+    x defaults write pro.writer.mac "Document Path Extension" -string "md"
     # iA Writer: disable night mode
     x defaults write pro.writer.mac nightMode -int 0
     # ia Writer: indent using spaces
     x defaults write pro.writer.mac "Editor Indent Using Spaces" -int 1
+    # iA Writer: use "Quattro" font
+    x defaults write pro.writer.mac "Editor Typeface" -int 2
+    # iA Writer: configure sidebar
+    x defaults write pro.writer.mac "Library Shows Search Bar" -int 0
+    x defaults write pro.writer.mac "Organizer Shows Favorites" -int 0
+    x defaults write pro.writer.mac "Organizer Shows Hashtags" -int 0
+    x defaults write pro.writer.mac "Organizer Shows Smart Folders" -int 0
 
     # Firefox, Safari: bind cmd-opt-j to "Web Console", to match Chrome (and muscle memory...)
     x defaults write org.mozilla.firefox NSUserKeyEquivalents -dict-add "Web Console" -string "@~j"
@@ -301,15 +236,6 @@ case "$PLATFORM" in
       x ln -s "$HOME/Library/Mobile Documents/com~apple~CloudDocs" "$HOME/iCloud"
     fi
 
-    ;;
-
-esac
-
-# Color Palettes
-
-case "$PLATFORM" in
-
-  darwin )
     # https://github.com/altercation/ethanschoonover.com/tree/master/projects/solarized/apple-colorpalette-solarized
     if [ ! -f "$DSTDIR/Library/Colors/Solarized.clr" ]; then
       x cp "$SRCDIR/etc/Solarized.clr" "$DSTDIR/Library/Colors"
@@ -318,22 +244,18 @@ case "$PLATFORM" in
     if [ ! -f "$DSTDIR/Library/Colors/Material-Design.clr" ]; then
       x cp "$SRCDIR/etc/Material-Design.clr" "$DSTDIR/Library/Colors"
     fi
-    ;;
 
-esac
-
-# Services
-
-case "$PLATFORM" in
-
-  darwin )
-    # Let's just assume Services is special...
+    # Let's just assume Services is special and copy instead of symlink...
     x rsync -a --delete "$SRCDIR/etc/Services/" "$DSTDIR/Library/Services/"
+
+    if [[ -x /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport ]]; then
+      x ln -sf /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport $BINDIR
+    fi
     ;;
 
 esac
 
-# fish
+heading "fish"
 
 # Fish configuration needs to be in ~/.config/fish
 
@@ -345,24 +267,18 @@ if [ ! -L "$HOME/.config/fish" ]; then
   x ln -s "$SRCDIR/fish" "$HOME/.config/fish"
 fi
 
-# Update completions
-if exists fish ; then
-  x fish -c fish_update_completions
+# Update completions if completions more than 7 days old
+if ! find $HOME/.local/share/fish/generated_completions -depth 0 -mtime 7 ; then
+  x echo fish -c fish_update_completions
 fi
 
 # Scripts for $LOCAL/bin
 
-# airport
-
-if [[ -x /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport ]]; then
-  x ln -sf /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport $BINDIR
-fi
-
-# brew
-
 if exists brew ; then
 
-  x brew update || exit # need to agree to license when xcode updates
+  heading "brew"
+
+  (brew update || exit) | grep -v "Already up-to-date." # need to agree to license when xcode updates
 
   # The non-HEAD version is 7 years old...
   if ! brew leaves | grep -q jed ; then
@@ -385,14 +301,16 @@ if exists brew ; then
   comm -13 <(brew leaves | sort) <(echo $expected | tr ' ' '\n' | sort) | xargs -n 1 brew install
   comm -23 <(brew leaves | sort) <(echo $expected $custom $optional | tr ' ' '\n' | sort) | xargs -n 1 brew remove
 
-  x brew upgrade --cleanup
-  x brew cleanup # --cleanup doesn't seem to always actually cleanup because brew...
+  brew upgrade --cleanup
+  brew cleanup # --cleanup doesn't seem to always actually cleanup because brew...
 
 fi
 
 # apt-get
 
 if exists apt-get && [ $SUDO -ne 1 ]; then
+
+  heading "apt-get"
 
   x sudo apt-get -y upgrade
 
@@ -406,53 +324,13 @@ if exists apt-get && [ $SUDO -ne 1 ]; then
 
 fi
 
-# npm
-
-# if exists npm ; then
-
-#   packages="docco eslint firebase-tools http-server npm-check-updates serve"
-
-#   for p in $packages ; do
-#     # Pipe to /dev/null to avoid pipe error when returning early via -q
-#     if ! npm -g ls --depth=0 --parseable=true | xargs -L 1 basename | grep -x $p > /dev/null ; then
-#       x npm -g install $p
-#     fi
-#   done
-
-#   # npm -g update does not work as expected but installing over the top
-#   # of the outdated package works; see
-#   # https://github.com/npm/npm/issues/10590#issuecomment-225844879
-#   for p in `npm -g outdated --parseable=true | cut -d : -f 4 | grep -v npm` ; do
-#     x npm -g install $p
-#   done
-
-# fi
-
-# yarn (Linux)
-
-# if [ "$PLATFORM" = "linux" ]; then
-
-#   if ! exists yarn ; then
-
-#     # TODO Add check for updates; see https://github.com/yarnpkg/yarn/issues/1139
-
-#     xmkdir "$LOCAL/yarn"
-#     curl -sL https://yarnpkg.com/latest.tar.gz | tar xz --strip 1 -C "$LOCAL/yarn"
-#     x ln -fs "$LOCAL/yarn/bin/yarn" "$BINDIR"
-
-#   fi
-
-# fi
-
-# git
+heading "git"
 
 if [ "$PLATFORM" = "darwin" ]; then
-
   git config --file ~/.gitconfig.local credential.helper osxkeychain
-
 fi
 
-# Visual Studio Code
+heading "vscode"
 
 # Don't use system tools to update VS Code
 if [ -e /etc/apt/sources.list.d/vscode.list ] && [ $SUDO -ne 1 ]; then
